# Generated by Django 5.0.14 on 2026-05-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntennaConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('antenna_config_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('rows', models.PositiveIntegerField()),
                ('cols', models.PositiveIntegerField()),
                ('polarization', models.CharField(choices=[('V', 'vertical'), ('H', 'horizontal'), ('VH', 'dual-VH'), ('cross', 'cross-polarized')], max_length=16)),
                ('pattern', models.CharField(choices=[('tr38901', '3GPP TR 38.901 sector'), ('dipole', 'dipole'), ('iso', 'isotropic'), ('hw_dipole', 'halfwave-dipole'), ('vh_dipole', 'VH dipole')], max_length=32)),
                ('vertical_spacing', models.FloatField(default=0.5)),
                ('horizontal_spacing', models.FloatField(default=0.5)),
                ('antenna_config_created_at', models.DateTimeField()),
                ('antenna_config_updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ru_antenna_config',
                'ordering': ['-antenna_config_updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cell_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('pci', models.IntegerField(db_index=True)),
                ('azimuth_deg', models.FloatField(default=0.0)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('position_z', models.FloatField()),
                ('frequency_ghz', models.FloatField(default=2.5)),
                ('bandwidth_mhz', models.FloatField(default=100.0)),
                ('cell_created_at', models.DateTimeField()),
                ('cell_updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ru_cell',
                'ordering': ['pci'],
            },
        ),
        migrations.CreateModel(
            name='UePosition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ue_position_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ue_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('position_z', models.FloatField()),
                ('velocity_x', models.FloatField(default=0.0)),
                ('velocity_y', models.FloatField(default=0.0)),
                ('velocity_z', models.FloatField(default=0.0)),
                ('ue_position_created_at', models.DateTimeField()),
                ('ue_position_updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ru_ue_position',
                'ordering': ['ue_id'],
            },
        ),
    ]
