# Generated by Django 5.0.14 on 2026-05-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antenna', '0002_cell_gnb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
