# Generated by Django 5.0.14 on 2026-05-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antenna', '0003_cell_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='power_dbm',
            field=models.FloatField(default=43.0),
        ),
    ]
