# Generated by Django 5.0.14 on 2026-05-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CellState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cell_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('cell_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('pci', models.IntegerField()),
                ('total_prb', models.IntegerField(default=273)),
                ('freq_ghz', models.FloatField(default=3.5)),
                ('bw_mhz', models.FloatField(default=100.0)),
                ('served_plmn', models.CharField(default='00101', max_length=16)),
                ('cell_created_at', models.BigIntegerField()),
                ('cell_updated_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'mac_cell_state',
            },
        ),
        migrations.CreateModel(
            name='UeMacState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ue_mac_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ue_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('serving_cell_id', models.CharField(db_index=True, max_length=64)),
                ('last_mcs_dl', models.IntegerField(default=9)),
                ('last_mcs_ul', models.IntegerField(default=9)),
                ('last_cqi', models.IntegerField(default=7)),
                ('last_sinr_db', models.FloatField(default=0.0)),
                ('last_pmi', models.IntegerField(default=0)),
                ('last_rank', models.IntegerField(default=1)),
                ('last_allocated_prb_dl', models.IntegerField(default=0)),
                ('last_allocated_prb_ul', models.IntegerField(default=0)),
                ('ue_mac_created_at', models.BigIntegerField()),
                ('ue_mac_updated_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'mac_ue_state',
            },
        ),
        migrations.CreateModel(
            name='HarqProcess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('harq_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('f_ue_mac_uuid', models.CharField(db_index=True, max_length=255)),
                ('harq_pid', models.IntegerField()),
                ('direction', models.CharField(choices=[('DL', 'DL'), ('UL', 'UL')], max_length=4)),
                ('state', models.CharField(choices=[('NEW', 'NEW'), ('WAIT_FEEDBACK', 'WAIT_FEEDBACK'), ('RETX', 'RETX'), ('DONE', 'DONE')], default='NEW', max_length=16)),
                ('retx_count', models.IntegerField(default=0)),
                ('last_tbs_bytes', models.IntegerField(default=0)),
                ('harq_updated_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'mac_harq_process',
                'unique_together': {('f_ue_mac_uuid', 'harq_pid', 'direction')},
            },
        ),
    ]
