# Generated by Django 4.2.30 on 2026-05-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mac', '0002_cellstate_gnb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellstate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
