# Generated by Django 5.0.14 on 2026-07-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('building_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('scene_id', models.CharField(blank=True, default='', max_length=128)),
                ('pos_x', models.FloatField(default=0)),
                ('pos_y', models.FloatField(default=0)),
                ('pos_z', models.FloatField(default=0)),
                ('size_x', models.FloatField(default=10)),
                ('size_y', models.FloatField(default=10)),
                ('size_z', models.FloatField(default=10)),
                ('color_r', models.FloatField(default=0.75)),
                ('color_g', models.FloatField(default=0.75)),
                ('color_b', models.FloatField(default=0.75)),
                ('usd_path', models.CharField(blank=True, default='', max_length=512)),
                ('preset_type', models.CharField(blank=True, default='', max_length=128)),
                ('target_height_m', models.FloatField(blank=True, null=True)),
                ('rot_x', models.FloatField(default=0)),
                ('rot_y', models.FloatField(default=0)),
                ('rot_z', models.FloatField(default=0)),
                ('material', models.CharField(blank=True, default='', max_length=128)),
                ('building_created_at', models.DateTimeField(auto_now_add=True)),
                ('building_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'building_object',
            },
        ),
        migrations.CreateModel(
            name='GnbConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gnb_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('freq_mhz', models.FloatField()),
                ('power_dbm', models.FloatField()),
                ('bw_hz', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('pos_x', models.FloatField(default=0)),
                ('pos_y', models.FloatField(default=0)),
                ('pos_z', models.FloatField(default=0)),
                ('color_r', models.FloatField(default=1.0)),
                ('color_g', models.FloatField(default=1.0)),
                ('color_b', models.FloatField(default=1.0)),
                ('target_height_m', models.FloatField(blank=True, null=True)),
                ('cells', models.JSONField(blank=True, default=list, null=True)),
                ('gnb_created_at', models.DateTimeField(auto_now_add=True)),
                ('gnb_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gnb_config',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scenario_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('scene_id', models.CharField(db_index=True, max_length=128)),
                ('raw_json', models.JSONField(default=dict)),
                ('duration_sec', models.FloatField(default=0.0)),
                ('tick_ms', models.IntegerField(default=500)),
                ('ue_count', models.IntegerField(default=0)),
                ('precompute_status', models.CharField(db_index=True, default='pending', max_length=32)),
                ('precompute_progress', models.FloatField(default=0.0)),
                ('precompute_error', models.TextField(blank=True, default='')),
                ('cache_path', models.CharField(blank=True, default='', max_length=512)),
                ('cache_size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scenario',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UeConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ue_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('waypoints_json', models.JSONField(default=list)),
                ('speed_mps', models.FloatField(default=1.0)),
                ('loop', models.BooleanField(default=True)),
                ('pos_x', models.FloatField(default=0)),
                ('pos_y', models.FloatField(default=0)),
                ('pos_z', models.FloatField(default=0)),
                ('color_r', models.FloatField(default=0.5)),
                ('color_g', models.FloatField(default=0.5)),
                ('color_b', models.FloatField(default=0.5)),
                ('usd_path', models.CharField(blank=True, default='', max_length=512)),
                ('preset_type', models.CharField(blank=True, default='', max_length=128)),
                ('target_height_m', models.FloatField(blank=True, null=True)),
                ('ue_created_at', models.DateTimeField(auto_now_add=True)),
                ('ue_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ue_config',
            },
        ),
    ]
