# Generated by Django 5.0.7 on 2026-04-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('drb_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ue_id', models.CharField(db_index=True, max_length=64)),
                ('drb_id', models.IntegerField()),
                ('qos_5qi', models.IntegerField()),
                ('rlc_mode', models.CharField(default='AM', max_length=4)),
                ('gtp_teid_ul', models.BigIntegerField()),
                ('gtp_teid_dl', models.BigIntegerField()),
                ('dl_packets', models.BigIntegerField(default=0)),
                ('ul_packets', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cu_up_drb',
                'ordering': ('ue_id', 'drb_id'),
                'unique_together': {('ue_id', 'drb_id')},
            },
        ),
    ]
