# Generated by Django 5.0.14 on 2026-05-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ru_state_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('sfn_counter', models.IntegerField(default=0)),
                ('slot_counter', models.IntegerField(default=0)),
                ('numerology', models.IntegerField(default=1)),
                ('fft_size', models.IntegerField(default=4096)),
                ('cp_type', models.CharField(default='normal', max_length=16)),
                ('last_tick_at', models.DateTimeField(blank=True, null=True)),
                ('ru_state_created_at', models.DateTimeField()),
                ('ru_state_updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ru_state',
            },
        ),
    ]
