# Generated by Django 5.0.14 on 2026-05-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TickState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tick_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('tick_count', models.BigIntegerField(default=0)),
                ('sfn', models.IntegerField(default=0)),
                ('slot', models.IntegerField(default=0)),
                ('started_at_ms', models.BigIntegerField(null=True)),
                ('last_tick_ms', models.BigIntegerField(default=0)),
                ('is_running', models.BooleanField(default=False)),
                ('tick_state_updated_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tick_state',
            },
        ),
    ]
