# Generated by Django 5.0.7 on 2026-04-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CellConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cell_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('cell_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('pci', models.IntegerField()),
                ('frequency_ghz', models.FloatField()),
                ('bandwidth_mhz', models.FloatField()),
                ('served_plmn', models.CharField(default='00101', max_length=16)),
                ('served_by_du_id', models.BigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cu_cp_cell_config',
                'ordering': ('cell_id',),
            },
        ),
        migrations.CreateModel(
            name='DuRegistry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('du_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('gnb_du_id', models.BigIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('served_cells_json', models.JSONField(default=list)),
                ('registered_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cu_cp_du_registry',
                'ordering': ('gnb_du_id',),
            },
        ),
        migrations.CreateModel(
            name='HandoverEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ho_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ue_id', models.CharField(db_index=True, max_length=64)),
                ('source_cell', models.CharField(max_length=64)),
                ('target_cell', models.CharField(max_length=64)),
                ('trigger', models.CharField(choices=[('A3_TTT', 'A3_TTT'), ('MANUAL', 'MANUAL')], default='A3_TTT', max_length=16)),
                ('status', models.CharField(choices=[('PREP', 'PREP'), ('EXEC', 'EXEC'), ('SUCC', 'SUCC'), ('FAIL', 'FAIL')], default='PREP', max_length=8)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cu_cp_handover_event',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='MeasurementLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meas_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ue_id', models.CharField(db_index=True, max_length=64)),
                ('rsrp_dbm', models.FloatField()),
                ('sinr_db', models.FloatField()),
                ('throughput_dl_mbps', models.FloatField(default=0.0)),
                ('throughput_ul_mbps', models.FloatField(default=0.0)),
                ('mcs_dl', models.IntegerField(default=0)),
                ('rb_width_dl', models.IntegerField(default=0)),
                ('mimo_rank', models.IntegerField(default=1)),
                ('neighbor_cells_json', models.JSONField(default=list)),
                ('recorded_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'cu_cp_measurement_log',
                'ordering': ('-recorded_at',),
            },
        ),
        migrations.CreateModel(
            name='UeContext',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ue_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ue_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('rrc_state', models.CharField(choices=[('IDLE', 'IDLE'), ('SETUP', 'SETUP'), ('CONNECTED', 'CONNECTED'), ('RELEASE', 'RELEASE'), ('INACTIVE', 'INACTIVE')], default='IDLE', max_length=16)),
                ('serving_cell', models.CharField(blank=True, default='', max_length=64)),
                ('rrc_ue_id', models.BigIntegerField(default=0)),
                ('amf_ue_ngap_id', models.BigIntegerField(default=0)),
                ('ran_ue_ngap_id', models.BigIntegerField(default=0)),
                ('gnb_du_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('last_measurement_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cu_cp_ue_context',
                'ordering': ('ue_id',),
            },
        ),
    ]
