# Generated by Django 5.0.7 on 2026-05-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cu_cp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellconfig',
            name='gnb_id',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
    ]
