# Generated by Django 5.0.7 on 2026-05-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cu_cp', '0002_cellconfig_gnb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellconfig',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
