# Generated by Django 5.0.7 on 2026-05-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cu_cp', '0003_cellconfig_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementlog',
            name='pdcp_sdu_volume_dl',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='measurementlog',
            name='pdcp_sdu_volume_ul',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='measurementlog',
            name='rlc_sdu_delay_dl_ms',
            field=models.FloatField(default=0.0),
        ),
    ]
