# Generated by Django 5.0.7 on 2026-05-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cu_cp', '0004_measurementlog_pdcp_sdu_volume_dl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uecontext',
            name='traffic_profile_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
