# Generated by Django 5.0.7 on 2026-08-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cu_cp', '0007_cellconfig_nr_cellid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoverevent',
            name='trigger',
            field=models.CharField(choices=[('A3_TTT', 'A3_TTT'), ('E2_RIC_CONTROL', 'E2_RIC_CONTROL'), ('MANUAL', 'MANUAL')], default='A3_TTT', max_length=16),
        ),
        migrations.CreateModel(
            name='CgiResolution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pci', models.IntegerField(db_index=True)),
                ('arfcn', models.IntegerField(db_index=True)),
                ('cgi', models.CharField(max_length=64)),
                ('plmn', models.CharField(default='', max_length=16)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cu_cp_cgi_resolution',
                'ordering': ('pci', 'arfcn'),
                'unique_together': {('pci', 'arfcn')},
            },
        ),
        migrations.CreateModel(
            name='NrCellRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_cell_id', models.CharField(db_index=True, max_length=64)),
                ('target_cgi', models.CharField(db_index=True, max_length=64)),
                ('target_pci', models.IntegerField()),
                ('target_arfcn', models.IntegerField()),
                ('target_rat', models.CharField(default='NR', max_length=8)),
                ('target_plmn', models.CharField(default='', max_length=16)),
                ('is_ho_allowed', models.BooleanField(default=True)),
                ('is_remove_allowed', models.BooleanField(default=True)),
                ('is_xn_allowed', models.BooleanField(default=True)),
                ('xn_x2_established', models.BooleanField(default=False)),
                ('ho_validated', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('ho_blocklist', models.BooleanField(default=False)),
                ('no_remove', models.BooleanField(default=False)),
                ('xn_blocklist', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cu_cp_nr_cell_relation',
                'ordering': ('source_cell_id', 'target_cgi'),
                'unique_together': {('source_cell_id', 'target_cgi')},
            },
        ),
    ]
