# Generated by Django 5.0.7 on 2026-08-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cu_cp', '0008_alter_handoverevent_trigger_cgiresolution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NrRelationChangeEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=16)),
                ('source_cell_id', models.CharField(db_index=True, max_length=64)),
                ('target_cgi', models.CharField(max_length=64)),
                ('by', models.CharField(default='xapp', max_length=32)),
                ('detail', models.CharField(blank=True, default='', max_length=128)),
                ('at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'cu_cp_nr_relation_change_event',
                'ordering': ('-at',),
            },
        ),
    ]
