# Generated by Django 5.0.7 on 2026-08-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cu_cp', '0009_nrrelationchangeevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RlfEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ue_id', models.CharField(db_index=True, max_length=64)),
                ('source_cell', models.CharField(db_index=True, max_length=64)),
                ('source_pci', models.IntegerField(default=-1)),
                ('sinr_at_rlf', models.FloatField(default=0.0)),
                ('t310_ms', models.FloatField(default=0.0)),
                ('reason', models.CharField(default='T310_EXPIRY', max_length=32)),
                ('reestab_cell', models.CharField(blank=True, default='', max_length=64)),
                ('reestab_pci', models.IntegerField(default=-1)),
                ('outcome', models.CharField(choices=[('DECLARED', 'DECLARED'), ('REESTAB_WITH_CTX', 'REESTAB_WITH_CTX'), ('REESTAB_WITHOUT_CTX', 'REESTAB_WITHOUT_CTX'), ('DROP', 'DROP')], default='DECLARED', max_length=24)),
                ('detected_at', models.DateTimeField(db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cu_cp_rlf_event',
                'ordering': ('-detected_at',),
            },
        ),
    ]
