# Generated by Django 5.0.7 on 2026-08-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cu_cp', '0010_rlfevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverevent',
            name='failure_cause',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='handoverevent',
            name='mro_class',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
