# Generated by Django 5.0.7 on 2026-08-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cu_cp', '0011_handoverevent_failure_cause_handoverevent_mro_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='RrcEstabCounter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cell_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('att', models.BigIntegerField(default=0)),
                ('succ', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cu_cp_rrc_estab_counter',
            },
        ),
    ]
