# Generated by Django 5.0.7 on 2026-08-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cu_cp', '0012_rrcestabcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellCumCounter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cell_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('session_time_sec', models.BigIntegerField(default=0)),
                ('conn_max', models.IntegerField(default=0)),
                ('conn_sum', models.BigIntegerField(default=0)),
                ('conn_n', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cu_cp_cell_cum_counter',
            },
        ),
        migrations.AddField(
            model_name='measurementlog',
            name='qos_5qi',
            field=models.IntegerField(default=9),
        ),
    ]
