# Generated by Django 5.0.7 on 2026-08-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cu_cp', '0014_cellconfig_is_barred'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementlog',
            name='serving_cell',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
