# Generated by Django 5.0.7 on 2026-08-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cu_cp', '0015_measurementlog_serving_cell'),
    ]

    operations = [
        migrations.CreateModel(
            name='E2Subscription',
            fields=[
                ('subscription_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('service_model', models.CharField(max_length=16)),
                ('ran_function_id', models.IntegerField()),
                ('action_definition', models.JSONField(default=dict)),
                ('event_trigger', models.JSONField(default=dict)),
                ('ric_req_id', models.JSONField(default=dict)),
                ('created_at_ms', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=16)),
            ],
            options={
                'db_table': 'cu_e2_subscription',
            },
        ),
    ]
