# Generated by Django 5.0.14 on 2026-05-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RlcEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rlc_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ue_id', models.CharField(db_index=True, max_length=64)),
                ('bearer_type', models.CharField(choices=[('SRB', 'SRB'), ('DRB', 'DRB')], max_length=4)),
                ('bearer_id', models.IntegerField()),
                ('mode', models.CharField(choices=[('AM', 'AM'), ('UM', 'UM'), ('TM', 'TM')], max_length=4)),
                ('sn_field_length', models.IntegerField(default=12)),
                ('tx_buffer_bytes', models.IntegerField(default=0)),
                ('rx_buffer_bytes', models.IntegerField(default=0)),
                ('retx_count', models.IntegerField(default=0)),
                ('status_pdu_pending', models.BooleanField(default=False)),
                ('rlc_created_at', models.BigIntegerField()),
                ('rlc_updated_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'rlc_entity',
                'unique_together': {('ue_id', 'bearer_type', 'bearer_id')},
            },
        ),
    ]
