# Generated by Django 5.0.14 on 2026-05-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='F1Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('f1_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('gnb_du_id', models.IntegerField()),
                ('cu_host', models.CharField(max_length=128)),
                ('cu_port', models.IntegerField()),
                ('transaction_id', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('INIT', 'INIT'), ('SETUP_SENT', 'SETUP_SENT'), ('ACTIVE', 'ACTIVE'), ('FAILED', 'FAILED')], default='INIT', max_length=16)),
                ('last_setup_at', models.BigIntegerField(null=True)),
                ('f1_session_updated_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'f1_session',
            },
        ),
    ]
