# Generated by Django 5.0.14 on 2026-05-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastTti',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_tti_uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('direction', models.CharField(max_length=4)),
                ('ue_id', models.CharField(db_index=True, max_length=128)),
                ('sfn', models.IntegerField()),
                ('slot', models.IntegerField()),
                ('sinr_db', models.FloatField()),
                ('cqi', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=1)),
                ('pmi', models.IntegerField(default=0)),
                ('harq_pid', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('last_tti_created_at', models.DateTimeField()),
                ('last_tti_updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ru_last_tti',
                'ordering': ['-last_tti_updated_at'],
                'unique_together': {('ue_id', 'direction')},
            },
        ),
    ]
